# Local Settings | Turn these on for local development
# baseurl: ""

# Github Pages Setting | Turn these on for github pages deployment
baseurl: "moaatt2/"


# Site settings
title: Dakota McKay
email: dakotamckay72@gmail.com
description: "Content: TODO | footer description"
url: ""
formspree_form_id: mqkvovpa

# Author Information
author:
  name: Dakota McKay
  email: dakotamckay72@gmail.com

# Version info for footer
github:
  versions:
    jekyll: "4.3.2"
    github-pages: "288"


# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# minima settings
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/moaatt2

    - platform: email
      user_url: "mailto:dakotamckay72@gmail.com"
      user_title: "dakotamckay72@gmail.com" 

    - platform: code
      user_url: "https://github.com/moaatt2/moaatt2"
      user_title: "moaatt2/moaatt2"

    - platform: rss
      user_url: "/feed.xml"
      user_title: "RSS Feed"

    # Potential future additions
    # - { platform: linkedin,       user_url: "" }
    # - { platform: stackoverflow,  user_url: "" }
    # - { platform: x,              user_url: "" }
    # - { platform: substack,       user_url: "" }
    # - { platform: devto,          user_url: "" }
    # - { platform: dribbble,       user_url: "" }
    # - { platform: facebook,       user_url: "" }
    # - { platform: flickr,         user_url: "" }
    # - { platform: google_scholar, user_url: "" }
    # - { platform: instagram,      user_url: "" }
    # - { platform: keybase,        user_url: "" }
    # - { platform: microdotblog,   user_url: "" }
    # - { platform: pinterest,      user_url: "" }
    # - { platform: telegram,       user_url: "" }
    # - { platform: youtube,        user_url: "" }
